/*
 * buzzer.h
 *
 * Non-blocking piezoelectric buzzer driver.
 * The buzzer is driven by GPIO PD0 (RCAP 'Sound' pin) through a
 * transistor buffer.  A ~500 Hz square wave is generated by toggling
 * the pin every 1 ms inside buzzer_task_execute().
 */

#ifndef BUZZER_H_
#define BUZZER_H_

void buzzer_init(void);

/* Call once to start a timed alert.  Subsequent calls restart the
   alert from the beginning.                                         */
void buzzer_trigger(void);

/* Call every iteration of the main loop (or at least every < 1 ms).
   Non-blocking: returns immediately.                                 */
void buzzer_task_execute(void);

#endif /* BUZZER_H_ */
